update action hooks

diff --git a/.openshift/action_hooks/deploy b/.openshift/action_hooks/deploy
--- a/.openshift/action_hooks/deploy
+++ b/.openshift/action_hooks/deploy
@@ -4,42 +4,42 @@
 # up again.  This script gets executed directly, so it could be python, php,
 # ruby, etc.
 
+source $OPENSHIFT_CARTRIDGE_SDK_BASH
+
+function ruby_with_nodejs_context {
+  case $OPENSHIFT_RUBY_VERSION in
+    1.8) /usr/bin/scl enable nodejs010 "$1" ;;
+    1.9) /usr/bin/scl enable nodejs010 ruby193 "$1" ;;
+  esac
+}
+
 set -e
 
-if [ -z "$OPENSHIFT_DB_HOST" ]
-then
-    echo 1>&2
-    echo "Could not find mysql database.  Please run:" 1>&2
-    echo "rhc app cartridge add -a $OPENSHIFT_APP_NAME -c mysql-5.1" 1>&2
-    echo "then make a sample commit (add whitespace somewhere) and re-push" 1>&2
-    echo 1>&2
+if [ ! -z "$OPENSHIFT_POSTGRESQL_DB_HOST" ]; then
+  export RAILS_DB="postgresql"
 fi
 
-RETRY=60
-while [ $RETRY -gt 0 ] ; do
-    #reload env variables
-    for env_var in  $OPENSHIFT_HOMEDIR/.env/*
-    do
-        . $env_var
-    done
+if [ ! -z "$OPENSHIFT_MYSQL_DB_HOST" ]; then
+  export RAILS_DB="mysql"
+fi
 
-    #check for db
-    if [ -n "$OPENSHIFT_DB_HOST" ]
-    then
-        echo "Database server found at $OPENSHIFT_DB_HOST. initializing..."
-        sleep 5
-        break
-    fi
-
-    sleep 1
-    RETRY=$(( $RETRY - 1 ))
-done
-
-if [ -z "$OPENSHIFT_DB_HOST" ]
-then
-    exit 5
+if [ -z "$RAILS_DB" ]; then
+  echo 1>&2
+  echo "Could not find the database cartridge.  Please run:" 1>&2
+  echo "rhc cartridge add -a $OPENSHIFT_APP_NAME -c mysql-5.1" 1>&2
+  echo "or"
+  echo "rhc cartridge add -a $OPENSHIFT_APP_NAME -c postgresql-9.2" 1>&2
+  echo "then make a sample commit (add whitespace somewhere) and re-push" 1>&2
+  echo 1>&2
+  exit 5
+else
+  if [ "$(type -t set_env_var)" == "function" ]; then
+    set_env_var 'RAILS_DB' $RAILS_DB $OPENSHIFT_HOMEDIR/.env/user_vars
+  fi
 fi
 
 pushd ${OPENSHIFT_REPO_DIR} > /dev/null
-bundle exec rake db:migrate RAILS_ENV="production"
+echo "exec rake db:migrate RAILS_ENV=${RAILS_ENV:-production}"
+ruby_with_nodejs_context "bundle exec rake db:migrate RAILS_ENV=${RAILS_ENV:-production}"
 popd > /dev/null
+
